{
 "title": "Blocks",
 "tags": [
  "stats",
  "blocks"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.blocks.currentSizeBytes)"
    },
    {
     "target": "aliasByMetric(stats.gauges.blocks.currentSizeWithWitnessBytes)"
    }
   ]
  },
  {
   "title": "Block Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.blocks.currentNumTransactions)"
    },
    {
     "target": "aliasByMetric(stats.gauges.blocks.currentSigOps)"
    },
    {
     "target": "aliasByMetric(stats.gauges.blocks.currentWeight)"
    }
   ]
  },
  {
   "title": "Blocks Received vs Block Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.blocks.currentHeight)"
    },
    {
     "target": "aliasByMetric(stats.message.received.block)"
    },
    {
     "target": "aliasByMetric(stats.message.received.cmpctblock)"
    }
   ]
  },
  {
   "title": "Blocks Received vs Block INVs Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.block, 'blockReceived')"
    },
    {
     "target": "alias(stats.message.received.cmpctblock, 'compactBlockReceived')"
    },
    {
     "target": "alias(stats.message.received.inv_block, 'blockInvReceived')"
    }
   ]
  },
  {
   "title": "Blocks Received vs Blocks Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.block, 'blockReceived')"
    },
    {
     "target": "alias(stats.message.received.cmpctblock, 'compactBlockReceived')"
    },
    {
     "target": "alias(stats.message.sent.block, 'blockSent')"
    },
    {
     "target": "alias(stats.message.received.getblocks, 'blocksRequested')"
    }
   ]
  }
 ]
}