{
 "title": "Overview",
 "description": "Realtime Bitcoin Node Stats",
 "tags": [
  "overview",
  "stats",
  "welcome"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "dashlist", "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 } },
  {
   "title": "localhost:8080",
   "type": "graph",
   "description": "localhost:8080",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.blocks.currentHeight, 'Block Height')"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.blocks.currentHeight, 'Block Height')"
    }
   ]
  },
  {
   "title": "Total Bitcoins in Existence",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.utxoset.totalBTCAmount, 'Total BTC')"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Peers" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.peers.fullNodeConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.spvNodeConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.inboundConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.outboundConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.knownAddresses)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.ipv4Connections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.ipv6Connections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.torConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.totalConnections)"
    }
   ]
  },
  {
   "title": "bytes Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.bandwidth.*.*.bytesSent" }
   ]
  },
  {
   "title": "bytes Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.bandwidth.*.*.bytesReceived"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  }
 ]
}