{
 "title": "P2P Messages",
 "tags": [
  "stats",
  "p2p"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "All Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Messages Received per sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(movingAverage(stats.message.received.*, 10), 3)"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "Messages Sent per sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(movingAverage(stats.message.sent.*, 10), 3)"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "addr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Messages Per Second" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.addr, 'addr messages received')"
    },
    {
     "target": "alias(stats.message.sent.addr, 'addr messages sent')"
    }
   ]
  },
  {
   "title": "getData",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Messages Per Second" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.getdata, 'getData messages received')"
    },
    {
     "target": "alias(stats.message.sent.getdata, 'getData messages sent')"
    }
   ]
  },
  {
   "title": "inv",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "Messages Per Second" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.inv, 'inv messages received')"
    },
    {
     "target": "alias(stats.message.sent.inv, 'inv messages sent')"
    }
   ]
  },
  {
   "title": "tx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "Messages Per Second" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.tx, 'tx messages received')"
    },
    {
     "target": "alias(stats.message.sent.tx, 'tx messages sent')"
    },
    {
     "target": "alias(divideSeries(stats.message.sent.tx, #A), 'ratio of tx sent:received')"
    }
   ]
  },
  {
   "title": "ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "Messages Per Second" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.ping, 'ping messages received')"
    },
    {
     "target": "alias(stats.message.sent.ping, 'ping messages sent')"
    }
   ]
  },
  {
   "title": "ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "Messages Per Second" }
   ],
   "targets": [
    {
     "target": "alias(stats.message.received.pong, 'pong messages received')"
    },
    {
     "target": "alias(stats.message.sent.pong, 'pong messages sent')"
    }
   ]
  }
 ]
}