{
 "title": "Peers",
 "tags": [
  "stats",
  "peers"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Peers" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.peers.fullNodeConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.spvNodeConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.inboundConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.outboundConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.knownAddresses)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.ipv4Connections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.ipv6Connections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.torConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.totalConnections)"
    }
   ]
  },
  {
   "title": "Peer Pings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs", "label": "Ping Time" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.peers.ping_us.lower)"
    },
    {
     "target": "aliasByMetric(stats.timers.peers.ping_us.median)"
    },
    {
     "target": "aliasByMetric(stats.timers.peers.ping_us.upper)"
    }
   ]
  },
  {
   "title": "Peer Misbehavior",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Rejected Messages per sec" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.message.sent.reject)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_tx_duplicate)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_tx_invalid)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_tx_nonstandard)"
    },
    {
     "target": "aliasByMetric(stats.misbehavior.banned)"
    },
    {
     "target": "stats.message.sent.reject_addr_malformed"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_block_)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_block_invalid)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_block_obsolete)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_headers_malformed)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_ping_malformed)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_sendcmpct_malformed)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_tx_insufficientfee)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_tx_malformed)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_version_duplicate)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_version_nonstandard)"
    },
    {
     "target": "aliasByMetric(stats.message.sent.reject_version_obsolete)"
    }
   ]
  }
 ]
}