{
 "title": "Stats Processing Stats",
 "tags": [ "stats" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stats Processed per Second By StatsD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scaleToSeconds(stats_counts.statsd.packets_received, 1)"
    }
   ]
  },
  {
   "title": "Carbon Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "carbon.agents.statoshi-a.memUsage"
    },
    {
     "target": "carbon.agents.statoshi-a.cache.queries"
    }
   ]
  },
  {
   "title": "Graphite Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.statsd.graphiteStats.calculationtime"
    },
    {
     "target": "stats.statsd.graphiteStats.flush_time"
    },
    {
     "target": "stats.statsd.graphiteStats.flush_length"
    }
   ]
  }
 ]
}