{
 "title": "System Metrics",
 "tags": [
  "stats",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.system.cpu.percent"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.gauges.system.load" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "stats.gauges.system.memory.used"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "stats.gauges.system.disk.size.used"
    },
    {
     "target": "stats.gauges.system.disk.read.bytes"
    },
    {
     "target": "stats.gauges.system.disk.write.bytes"
    }
   ]
  }
 ]
}