{
 "title": "Transactions",
 "tags": [
  "stats",
  "txs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transaction Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Transactions" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.transactions.txCacheSize)"
    },
    {
     "target": "aliasByMetric(stats.gauges.transactions.txInMemoryPool)"
    }
   ]
  },
  {
   "title": "Transactions Accepted Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Transactions Accepted" }
   ],
   "targets": [
    {
     "target": "alias(stats.transactions.accepted, 'txAccepted')"
    },
    {
     "target": "alias(stats.gauges.transactions.txRate, 'TX/S trailing month average')"
    }
   ]
  },
  {
   "title": "Transactions Accepted vs Rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "% Tx Accepted vs Received" }
   ],
   "targets": [
    {
     "target": "alias(stats.transactions.accepted, 'txAccepted')"
    },
    {
     "target": "alias(diffSeries(stats.message.received.tx, #A), 'txMessagesRejected')"
    }
   ]
  },
  {
   "title": "BTC Spent Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Bitcoins Spent" }
   ],
   "targets": [
    {
     "target": "alias(scale(stats.transactions.inputValue, 1e-8), 'BTC')"
    }
   ]
  },
  {
   "title": "% Transaction Inputs vs Outputs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.transactions.inputs)"
    },
    {
     "target": "aliasByMetric(stats.transactions.outputs)"
    }
   ]
  },
  {
   "title": "vbytes Per Transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(stats.transactions.sizeBytes, #B), 'Total TX vbytes / # TX')"
    }
   ]
  },
  {
   "title": "Fees (satoshis) Paid Per Transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(stats.transactions.fees, #B), 'Fees in satoshis / TX')"
    }
   ]
  },
  {
   "title": "Transaction Fees (satoshis) Paid Per vbyte",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(stats.transactions.fees, #B), 'Fees in satoshis / TX vbyte')"
    }
   ]
  },
  {
   "title": "Signature Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.transactions.sigOps)"
    }
   ]
  },
  {
   "title": "Total Historical Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.transactions.totalCount"
    }
   ]
  }
 ]
}