{
 "title": "Unspent Transaction Output Set",
 "tags": [
  "stats",
  "utxo"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Transactions With Unspent Outputs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.tx)"
    }
   ]
  },
  {
   "title": "Unspent Transaction Outputs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Unspent Transaction Outputs" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.txOutputs)"
    }
   ]
  },
  {
   "title": "Size of Serialized UTXO Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.dbSizeBytes)"
    }
   ]
  },
  {
   "title": "Total Bitcoins in Existence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.totalBTCAmount)"
    }
   ]
  }
 ]
}