diff a/GNUmakefile b/GNUmakefile	(rejected hunks)
@@ -210,74 +101,11 @@ CMD_ARGUMENTS							:= $(cmd)
 endif
 export CMD_ARGUMENTS
 
-# ref: https://github.com/linkit-group/dockerbuild/blob/master/makefile
-# if you see pwd_unknown showing up, check user permissions.
-#todo: more umbrel support
-#todo: umbrel root no good
-#todo: ref: https://github.com/getumbrel/umbrel/blob/master/security.md
-ifeq ($(umbrel),true)
-#comply with umbrel conventions
-PWD=/home/umbrel/umbrel/apps/$(PROJECT_NAME)
-UMBREL=true
-else
-pwd ?= pwd_unknown
-UMBREL=false
-endif
-export PWD
-export UMBREL
-#######################
-
 .PHONY: help
-help:
-	@echo ''
-	@echo '	[USAGE]:	make [BUILD] run [EXTRA_ARGUMENTS]	'
+help: report
 	@echo ''
-	@echo '		make init header build run user=root uid=0 nocache=false verbose=true'
 	@echo ''
-	@echo '	[DEV ENVIRONMENT]:	'
 	@echo ''
-	@echo '		make header user=root'
-	@echo '		make shell  user=root'
-	@echo '		make shell  user=$(HOST_USER)'
-	@echo ''
-	@echo '	[EXTRA_ARGUMENTS]:	set build variables	'
-	@echo ''
-	@echo '		nocache=true'
-	@echo '		            	add --no-cache to docker command and apk add $(NOCACHE)'
-	@echo '		port=integer'
-	@echo '		            	set PUBLIC_PORT default 80'
-	@echo ''
-	@echo '		nodeport=integer'
-	@echo '		            	set NODE_PORT default 8333'
-	@echo ''
-	@echo '		            	TODO'
-	@echo ''
-	@echo '	[DOCKER COMMANDS]:	push a command to the container	'
-	@echo ''
-	@echo '		cmd=command 	'
-	@echo '		cmd="command"	'
-	@echo '		             	send CMD_ARGUMENTS to the [TARGET]'
-	@echo ''
-	@echo '	[EXAMPLE]:'
-	@echo ''
-	@echo '		make all run user=root uid=0 no-cache=true verbose=true'
-	@echo '		make report all run user=root uid=0 no-cache=true verbose=true cmd="top"'
-	@echo '		make a r port=80 no-cache=true verbose=true cmd="ls"'
-	@echo ''
-	@echo '	[COMMAND_LINE]:'
-	@echo ''
-	@echo '	stats-console              # container command line'
-	@echo '	stats-bitcoind             # start container bitcoind -daemon'
-	@echo '	stats-debug                # container debug.log output'
-	@echo '	stats-whatami              # container OS profile'
-	@echo ''
-	@echo '	stats-cli -getmininginfo   # report mining info'
-	@echo '	stats-cli -gettxoutsetinfo # report txo info'
-	@echo ''
-	@echo '	#### WARNING: (effects host datadir) ####'
-	@echo '	'
-	@echo '	stats-prune                # default in bitcoin.conf is prune=1 - start pruning node'
-	@echo '	'
 
 .PHONY: report
 report:
