site_name: Pretty Good Privacy Guide
site_url: https://www.pgp.guide
repo_url: https://github.com/pgp-guide/pgp.guide
docs_dir: source
site_dir: docs
markdown_extensions:
    - pymdownx.striphtml:
        strip_comments: true
        strip_js_on_attributes: false
