#!/bin/bash -e

export LC_ALL=C

start_bitcoind(){
  BITCOIND=/usr/bin/bitcoind
    if test -f "$BITCOIND"; then
      /usr/local/bin/./bitcoind -daemon -prune=550 &
    fi
}
stop_bitcoind(){
  BITCOIN_CLI=/usr/bin/bitcoin-cli
    if test -f "$BITCOIN_CLI"; then
      /usr/bin/./bitcoin-cli stop &
    fi
}
shutdown(){

  echo "shutting down container"

  stop_bitcoind

  # first shutdown any service started by runit
  for _srv in $(ls -1 /etc/service); do
    sv force-stop $_srv
  done

  echo "shutting down runsvdir"

  # shutdown runsvdir command
  kill -HUP $RUNSVDIR
  wait $RUNSVDIR

  # give processes time to stop
  sleep 0.5

  echo "killing rest processes"
  # kill any other processes still running in the container
  for _pid  in $(ps -eo pid | grep -v PID  | tr -d ' ' | grep -v '^1$' | head -n -6); do
    timeout -t 5 /bin/sh -c "kill $_pid && wait $_pid || kill -9 $_pid"
  done
  exit
}

/usr/local/bin/./bitcoind -daemon -prune=550 &


su-exec root /usr/local/bin/./run-grafana.sh &

. /opt/graphite/bin/activate

echo

PATH="${PATH}:/usr/local/bin"

# run all scripts in the run_once folder
[ -d /etc/run_once ] && /bin/run-parts /etc/run_once

## check services to disable
for _srv in $(ls -1 /etc/service); do
    eval X=$`echo -n $_srv | tr [:lower:]- [:upper:]_`_DISABLED
    [ -n "$X" ] && touch /etc/service/$_srv/down
done

# remove stale pids
find /opt/graphite/storage -maxdepth 1 -name '*.pid' -delete

# chmod logrotate file (#111)
chmod 0644 /etc/logrotate.d/*

exec runsvdir -P /etc/service &
RUNSVDIR=$!
echo "Started runsvdir, PID is $RUNSVDIR"
echo "wait for processes to start...."

sleep 5
for _srv in $(ls -1 /etc/service); do
    sv status $_srv
done

# catch shutdown signals
trap shutdown SIGTERM SIGHUP SIGQUIT SIGINT
wait $RUNSVDIR

shutdown
