#!/bin/bash -e

export LC_ALL=C

BITCOIND=/usr/bin/local/bitcoind
#BITCOIND=/home/root/stats.bitcoincore.dev/conf/usr/bin/local/bitcoind
BITCOIN_CLI=/usr/local/bin/bitcoin-cli
PATH="${PATH}:/usr/local/bin"

start_bitcoind(){

echo "################################### start_bitcoind ##################################"

    if test -f "$BITCOIND"; then
      #REF: conf/docker-compose.yml and make init
      #su-exec root $BITCOIND -daemon -prune=550 -datadir=/root/.bitcoin
      su-exec root $BITCOIND -daemon -prune=550 -datadir=/root/.bitcoin
    fi
}
stop_bitcoind(){

echo "################################### stop_bitcoind ##################################"

    if test -f "$BITCOIN_CLI"; then
      su-exec root $BITCOIN_CLI stop
    fi
}
shutdown(){

  echo "shutting down container"

  stop_bitcoind

  # first shutdown any service started by runit
  for _srv in $(ls -1 /etc/service); do
    sv force-stop $_srv
  done

  echo "shutting down runsvdir"

  # shutdown runsvdir command
  kill -HUP $RUNSVDIR
  wait $RUNSVDIR

  # give processes time to stop
  sleep 0.5

  echo "killing rest processes"
  # kill any other processes still running in the container
  for _pid  in $(ps -eo pid | grep -v PID  | tr -d ' ' | grep -v '^1$' | head -n -6); do
    timeout -t 5 /bin/sh -c "kill $_pid && wait $_pid || kill -9 $_pid"
  done
  exit
}

echo "################################### entrypoint ##################################"

start_bitcoind &

#su-exec root bitcoind -daemon -prune=550 -datadir=/root/.bitcoin &

su-exec root /usr/local/bin/./run-grafana.sh &

. /opt/graphite/bin/activate


# run all scripts in the run_once folder
[ -d /etc/run_once ] && /bin/run-parts /etc/run_once

## check services to disable
for _srv in $(ls -1 /etc/service); do
    eval X=$`echo -n $_srv | tr [:lower:]- [:upper:]_`_DISABLED
    [ -n "$X" ] && touch /etc/service/$_srv/down
done

# remove stale pids
find /opt/graphite/storage -maxdepth 1 -name '*.pid' -delete

# chmod logrotate file (#111)
chmod 0644 /etc/logrotate.d/*

exec runsvdir -P /etc/service &
RUNSVDIR=$!
echo "Started runsvdir, PID is $RUNSVDIR"
echo "wait for processes to start...."

sleep 5
for _srv in $(ls -1 /etc/service); do
    sv status $_srv
done

# catch shutdown signals
trap shutdown SIGTERM SIGHUP SIGQUIT SIGINT
wait $RUNSVDIR

shutdown
