{
 "title": "Fee Estimates",
 "tags": [
  "stats",
  "fees"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Recommended Transaction Fee for Target Confirmation in X Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Satoshis / byte" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block1, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block2, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block3, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block4, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block5, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block10, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block20, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block100, 0.001), 4)"
    },
    {
     "target": "aliasByNode(scale(stats.gauges.estimates.fee.block1000, 0.001), 4)"
    }
   ]
  },
  {
   "title": "Average Network Transaction Fees per Byte",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Satoshis / byte" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(stats.transactions.fees, #B), 'Fee per byte')"
    }
   ]
  },
  {
   "title": "Network Transaction Fees per Byte Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Satoshis / byte" }
   ],
   "targets": [
    {
     "target": "alias(removeAbovePercentile(divideSeries(stats.transactions.fees, #B), 1), 'Lowest percentile fee rate')"
    },
    {
     "target": "alias(removeBelowPercentile(divideSeries(stats.transactions.fees, #B), 99), 'Highest percentile fee rate')"
    }
   ]
  }
 ]
}