{
 "title": "Function Timings",
 "tags": [ "stats" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AcceptBlock",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.AcceptBlock_us.mean)"
    }
   ]
  },
  {
   "title": "CheckBlock",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.CheckBlock_us.mean)"
    }
   ]
  },
  {
   "title": "ConnectBlock",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.ConnectBlock_ms.mean)"
    }
   ]
  },
  {
   "title": "ConnectTip",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.ConnectTip_ms.mean)"
    }
   ]
  },
  {
   "title": "AcceptToMemoryPool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.AcceptToMemoryPool_ms.lower)"
    },
    {
     "target": "aliasByMetric(stats.timers.AcceptToMemoryPool_ms.median)"
    },
    {
     "target": "aliasByMetric(stats.timers.AcceptToMemoryPool_ms.upper)"
    }
   ]
  },
  {
   "title": "CheckInputs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.CheckInputs_ms.lower)"
    },
    {
     "target": "aliasByMetric(stats.timers.CheckInputs_ms.median)"
    },
    {
     "target": "aliasByMetric(stats.timers.CheckInputs_ms.upper)"
    }
   ]
  },
  {
   "title": "CheckTransaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.CheckTransaction_us.lower)"
    },
    {
     "target": "aliasByMetric(stats.timers.CheckTransaction_us.median)"
    },
    {
     "target": "aliasByMetric(stats.timers.CheckTransaction_us.upper)"
    }
   ]
  }
 ]
}